name: CI

on: [push]

jobs:
  build-test:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.3', '8.0', '8.2']

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.version }}
    - name: Run PHP Unit tests
      shell: bash
      run: vendor/bin/phpunit --coverage-text
